// LOCALHOST FOR USER
### All Users
GET http://localhost:8080/user

### Single User
GET http://localhost:8080/user/65ba10a68e0397f5bb5b5d46

### Create a User
POST http://localhost:8080/user HTTP/1.1
content-Type: application/json

{
    "firstName": "Randalf",
    "lastName": "Ehigiator",
    "email": "randalf@gmail.com",
    "password": "newPass123"
}

### Update a User
PUT http://localhost:8080/user/65ba10a68e0397f5bb5b5d46 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Dove",
    "lastName": "Smith",
    "email": "dove.smith@email.com",
    "password": "oldPass123"
}

### Delete a User
DELETE http://localhost:8080/user/65ba1f6245a78fb5c8049a18 HTTP/1.1

// PRODUCTION FOR USER
### Get all Users
GET https://cse341-3-4.onrender.com/user HTTP/1.1

### Get Single User
GET https://cse341-3-4.onrender.com/user/65ba10d8976be7b34552f52a HTTP/1.1

### Create a User
POST https://cse341-3-4.onrender.com/user HTTP/1.1
content-Type: application/json

{
    "firstName": "Randalf",
    "lastName": "Ehigiator",
    "email": "randalf@gmail.com",
    "password": "PassOld123"  
}

### Update a User
PUT https://cse341-3-4.onrender.com/user/65ba15523ad220dfe6a1f0ab HTTP/1.1
Content-Type: application/json

{
    "firstName": "Dove",
    "lastName": "Smith",
    "email": "dove.smith@email.com",
    "password": "PassNew123"
}

### Delete a User
DELETE https://cse341-3-4.onrender.com/user/65ba17233ad220dfe6a1f0ac HTTP/1.1


// LOCALHOST FOR EMPLOYEES
### All Employees
GET http://localhost:8080/employee

### Single EMployee
GET http://localhost:8080/employee/65ba10fd8e0397f5bb5b5d47

### Create an Employee
POST http://localhost:8080/employee HTTP/1.1
content-Type: application/json

{
      "empId": "E011",
      "position": "Administrative Assistant II",
      "department": "Administration",
      "salary": 48000,
      "birthdate": "1994-06-28",
      "empDate": "2023-02-14",
      "empStatus": "Active"
}

### Update an Employee
PUT http://localhost:8080/employee/65ba1ad01cc6b4a9acc90cc3 HTTP/1.1
Content-Type: application/json

{
    "empId": "E021",
    "position": "Administrative Assistant II",
    "department": "Administration",
    "salary": 48000,
    "birthdate": "1994-06-28",
    "empDate": "2023-02-14",
    "empStatus": "Inactive"
}

### Delete an Employee
DELETE http://localhost:8080/employee/65ba1fab45a78fb5c8049a19 HTTP/1.1

// PRODUCTION
### Get all Employees
GET https://cse341-3-4.onrender.com/employee HTTP/1.1

### Get Single Employee
GET https://cse341-3-4.onrender.com/employee/65ba17603ad220dfe6a1f0ad HTTP/1.1

### Create an Employee
POST https://cse341-3-4.onrender.com/employee HTTP/1.1
content-Type: application/json

{
    "empId": "E011",
    "position": "Administrative Assistant II",
    "department": "Administration",
    "salary": 48000,
    "birthdate": "1994-06-28",
    "empDate": "2023-02-14",
    "empStatus": "Active"    
}

### Update an Employee
PUT https://cse341-3-4.onrender.com/employee/65ba17603ad220dfe6a1f0ad HTTP/1.1
Content-Type: application/json

{
    "empId": "E021",
    "position": "Administrative Assistant III",
    "department": "Administration",
    "salary": 48000,
    "birthdate": "1994-06-28",
    "empDate": "2023-02-14",
    "empStatus": "Inactive"
}

### Delete an Employee
DELETE https://cse341-3-4.onrender.com/employee/65ba20bec96458154e74e9ca HTTP/1.1